server:
  port: 9030

spring:
  application:
    name: eureka-service-consume

eureka:
  instance:
    appname: eureka-service-consume
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka,http://127.0.0.1:8091/eureka,http://127.0.0.1:8092/eureka

feign:
  client:
    config:
      default:
        connectTimeout: 12000
        readTimeout: 12000
        loggerLevel: basic

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
