server:
  port: 8086

spring:
  application:
    name: eureka-service-provider

eureka:
  instance:
    appname: eureka-service-provider
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8080/eureka/

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info
info:
  app.name: taosun-microservicecloud
  company.name: www.taosun.com
  build.artifactId: ${project.artifactId}
  build.version: ${project.version}