server:
  port: 9010

spring:
  application:
    name: springcloud-config-server

  cloud:
    config:
      server:
        git:
          uri: https://gitee.com/xiaodingfeng/common-config.git
          default-label: master #默认是master 分支

eureka:
  instance:
    appname: springcloud-config-server
    instance-id: ${spring.application.name}:${random.value}
    prefer-ip-address: true
  client:
    service-url:
      defaultZone: http://127.0.0.1:8090/eureka,http://127.0.0.1:8091/eureka,http://127.0.0.1:8092/eureka

management:
  endpoints:
    web:
      exposure:
        include: refresh,health,info

